version: 0.2

phases:
  install:
    commands:
      - echo installing... inital package install
      - npm install
  pre_build:
    commands:
      - echo Prebuild... installing npm packages
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*